### PR TITLE
Clear scratch structures if search terminates exceptionally

### LINKED ISSUE #336: JVector should clear scratch search structures when a search terminates exceptionally
A GraphSearcher maintains scratch search data structures and asserts that these are empty when resuming, as the previous search should have emptied their contents. If a query terminates exceptionally, these should be cleared in an exception handler, to ensure they're in a good state for the next search.

### PR DESCRIPTION
**Pull request by jkni**
Code asserts that previous runs emptied the scratch structures, which happens at the end of the query.

Closes #336

### CODE REVIEW

File: jvector-base/src/main/java/io/github/jbellis/jvector/graph/GraphSearcher.java [hunk 1]
```diff
@@ -246,123 +246,130 @@ SearchResult searchInternal(SearchScoreProvider scoreProvider,
...
             }
+            // that should be everything
+            assert popFromQueue.size() == 0;
 
-            worstApproximateInTopK = Float.POSITIVE_INFINITY;
-            popFromQueue = approximateResults;
-        } else {
-            worstApproximateInTopK = approximateResults.rerank(topK, scoreProvider.reranker(), rerankFloor, rerankedResults, evictedResults);
+            return new SearchResult(nodes, numVisited, worstApproximateInTopK);
+        } catch (Exception e) {
```
Comment (eolivelli) [inline jvector-base/src/main/java/io/github/jbellis/jvector/graph/GraphSearcher.java]: Dummy question: why Exception and not Throwable ?

**Review by eolivelli — APPROVED** [review]
+1

File: jvector-base/src/main/java/io/github/jbellis/jvector/graph/GraphSearcher.java (hunk 1 above)
Comment (jkni) [reply jvector-base/src/main/java/io/github/jbellis/jvector/graph/GraphSearcher.java]: I think you're right and we should catch throwable here. In the event the throwable is recovered from by calling code, we should still correct the state as possible.
